name: ci

on:
  push:
    branches: main

jobs:
  path-context:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push 1.4.0
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./1.4.0/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            hybridadmin/dnsdist:1.4.0
      -
        name: Build and push 1.5.0
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./1.5.0/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            hybridadmin/dnsdist:1.5.0
      -
        name: Build and push master
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./master/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            hybridadmin/dnsdist:master
      -
        name: Build and push latest
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./1.5.0/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            hybridadmin/dnsdist:latest
      -
        name: Update Repo Readme/Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: hybridadmin/dnsdist
          readme-filepath: ./README.md
